version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ai-web-builder
    restart: always
    environment:
      POSTGRES_USER: postgres-ai
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: ai_web_builder_db
    ports:
      - '5438:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: